# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  # - release
  - nightly
notifications:
  email: false

branches:
  only: master

before_install:
  - julia -e 'Pkg.add("DataStructures"); Pkg.checkout("DataStructures")'

after_success:
  - julia -e 'cd(Pkg.dir("SpatialFields")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("SpatialFields"); Pkg.test("SpatialFields"; coverage=true)'
